# Generated by Django 5.0.3 on 2024-03-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeyapp', '0002_alter_game_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='image',
            field=models.CharField(max_length=2000),
        ),
    ]
