# Generated by Django 5.0.3 on 2024-03-23 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journeyapp', '0003_alter_wishlist_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='data_wished',
            new_name='date_wished',
        ),
    ]
